### ISSUE TITLE
Suggestion: Make narrowing down with filters more intuitive

### ISSUE THREAD

**Issue by Aixata** [lucca180/itemdb#10]
Example: I want to search all items with a restock profit of 10 000 and then want to narrow it down by category. 

Issue: The number near the other filters currently display the total amount in the database instead of the amount in the query. Multiple categories would have "CatName [126]" despite none of the items matching that additional filter.

Possible solution: Something like "CatName [x/126]" where x is the amount of items with that category in the current query, ideally sorted by x > 0 to avoid scrolling.

**Comment by lucca180** [comment]
Yeah, that makes sense. Can't promise that we will do it (cause we want the "stats counter" to be simple and fast) but just added to our list.

Thanks :)
